run:
	python main.py \
	--min-alcohol 14.13 \
	--alcohol 1.74 \
	--ash 2.33 \
	--alcalinity_of_ash 15.5 \
	--magnesium 127 \
	--total_phenols 2.7 \
	--flavanoids 3.05 \
	--nonflavanoid_phenols .27 \
	--proanthocyanins 2.28 \
	--color_intensity 5.63 \
	--hue 1.03 \
	--od_diluted_wines 3.82 \
	--proline 1065